sudo: false
language: node_js

node_js:
  - node 

cache:
  directories:
    - node_modules

branches:
   only:
      - master # will only build for master branch commits


before_script:
  - npm uninstall
  - npm install -g --silent firebase-tools
  - npm install

script: # the build step
  - ng build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive